# Generated by Django 5.0.4 on 2026-01-20 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="系统 ID",
                    ),
                ),
                ("body", models.TextField(max_length=200000, verbose_name="反馈内容")),
                (
                    "feishu_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="飞书ID"
                    ),
                ),
                (
                    "completion_rate",
                    models.IntegerField(default=0, verbose_name="完成度"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="状态"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passagefy_feedback_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈",
                "verbose_name_plural": "反馈",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="附件")),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passagefy_feedback_attachments",
                        to="passagefy.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "附件",
                "verbose_name_plural": "附件",
            },
        ),
    ]
