# Generated by Django 5.0.4 on 2026-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "passagefy",
            "0002_alter_feedback_created_at_alter_feedback_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="completion_rate",
            field=models.FloatField(default=0, verbose_name="完成度"),
        ),
    ]
